version: 2.1

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: 
          name: Docker build
          command: |
            docker build -t $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME .
      - run:
          name: Docker push
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin
            docker push $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME

workflows:
  main:
    jobs:
      - build